lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    bond_timeout: 4.0
    node_names: [
      'map_saver', 
      'controller_server', 
      'planner_server', 
      'behavior_server', 
      'bt_navigator', 
      'waypoint_follower', 
      'velocity_smoother'
    ]
    
bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 100
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator/NavigateThroughPosesNavigator"
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.

    # plugin_lib_names is used to add custom BT plugins to the executor (vector of strings).
    # Built-in plugins are added automatically
    # plugin_lib_names: []

    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:
  ros__parameters:
    controller_frequency: 10.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 3.0
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]
    use_realtime_priority: false

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 15.0
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      holonomic: true                  # Rất quan trọng cho Mecanum
      prune_plan: true
      prune_distance: 1.0
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      transform_tolerance: 0.2        # Tăng từ 0.1 lên 1.0 để tránh lỗi TF
      min_vel_x: 0.0                   # Tốc độ tiến tối thiểu
      min_vel_y: 0.0                   # Tốc độ ngang tối thiểu
      max_vel_x: 0.2                   # Phải khớp với velocity_smoother
      max_vel_y: 0.15                   # Phải khớp với velocity_smoother
      max_vel_theta: 0.8               # Phải khớp với velocity_smoother
      min_speed_xy: 0.0
      max_speed_xy: 0.2
      min_speed_theta: 0.0
      acc_lim_x: 1.0
      acc_lim_y: 0.5
      acc_lim_theta: 1.5
      decel_lim_x: -1.5
      decel_lim_y: -0.5
      decel_lim_theta: -1.5
      # Phần critics (tính toán đường đi) 
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle:
        scale: 15.0
        summation_scale: 1.0
      PathDist:
        scale: 5.0
        pdist_scale: 0.75
      GoalDist:
        scale: 4.0
        pdist_scale: 0.75
      RotateToGoal:
        scale: 2.0
        slow_down_angle: 0.5
        lookahead_time: -1.0
      GoalAlign:
        scale: 3.0
      PathAlign:
        scale: 4.0
      Oscillation:
        scale: 1.0
        oscillation_reset_dist: 0.05


local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 1.0
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      #robot_radius: 0.22
      # footprint: "[[x_fl, y_fl], [x_fr, y_fr], [x_rr, y_rr], [x_rl, y_rl]]"
      footprint: "[[0.12, 0.105], [0.12, -0.105], [-0.12, -0.105], [-0.12, 0.105]]"
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0
        inflation_radius: 0.22
      obstacle_layer:  # Thêm cái này
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 3.0
          obstacle_min_range: 0.0
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 0.5
      global_frame: map
      robot_base_frame: base_footprint
      #robot_radius: 0.22
      footprint: "[[0.12, 0.105], [0.12, -0.105], [-0.12, -0.105], [-0.12, 0.105]]"
      resolution: 0.05
      track_unknown_space: true
      rolling_window: false
      plugins: ["static_layer", "inflation_layer"]
      static_layer:                 # <-- THÊM MỤC NÀY
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        subscribe_to_updates: true    # Rất quan trọng để cập nhật bản đồ từ SLAM
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0
        inflation_radius: 0.22
      always_send_full_costmap: True

# The yaml_filename does not need to be specified since it going to be set by defaults in launch.
# If you'd rather set it in the yaml, remove the default "map" value in the tb3_simulation_launch.py
# file & provide full path to map below. If CLI map configuration or launch default is provided, that will be used.
map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 3.0
    planner_plugins: ["GridBased"]
    costmap_update_timeout: 1.0
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 5.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    loop_rate: 5
    stop_on_failure: false
    action_server_result_timeout: 900.0
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 1

#route_server:
  #ros__parameters:
    # The graph_filepath does not need to be specified since it going to be set by defaults in launch.
    # If you'd rather set it in the yaml, remove the default "graph" value in the launch file(s).
    # file & provide full path to map below. If graph config or launch default is provided, it is used
    # graph_filepath: $(find-pkg-share nav2_route)/graphs/aws_graph.geojson
    # boundary_radius_to_achieve_node: 1.0
    # radius_to_achieve_node: 2.0
    # smooth_corners: true
    # operations: ["AdjustSpeedLimit", "ReroutingService", "CollisionMonitor"]
    # ReroutingService:
    #   plugin: "nav2_route::ReroutingService"
    # AdjustSpeedLimit:
    #   plugin: "nav2_route::AdjustSpeedLimit"
    # CollisionMonitor:
    #   plugin: "nav2_route::CollisionMonitor"
    #   max_collision_dist: 3.0
    # edge_cost_functions: ["DistanceScorer", "CostmapScorer"]
    # DistanceScorer:
    #   plugin: "nav2_route::DistanceScorer"
    # CostmapScorer:
    #   plugin: "nav2_route::CostmapScorer"

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 5.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.2, 0.15, 0.8]
    min_velocity: [-0.2, -0.15, -0.8]
    max_accel: [1.0, 0.5, 1.5]
    max_decel: [-1.0, -0.5, -1.5]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop", "slowdown" and "limit" action types,
    # and robot footprint for "approach" action type.
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "/local_costmap/published_footprint"
      time_before_collision: 2.0
      simulation_time_step: 0.1
      min_points: 6
      visualize: False
      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "scan"
      min_height: 0.15
      max_height: 2.0
      enabled: True
